export const presetOptionsData = {
  en: {
    lightingStyles: [
      // --- Basic & Time of Day ---
      'Natural Sunlight', 'Golden Hour', 'Blue Hour', 'Overcast', 'Harsh midday sun', 'Dawn', 'Dusk', 'Moonlight', 'Starlight', 'Misty morning light', 'Afternoon sun', 'Twilight',
      // --- Artificial & Studio ---
      'Studio Lighting', 'Key light', 'Fill light', 'Three-point lighting', 'Rembrandt lighting', 'Butterfly lighting', 'Loop lighting', 'Split-lighting', 'Soft Light', 'Hard Light', 'Spotlight', 'Stage Lights', 'Ring light', 'Softbox light', 'Barn door lighting', 'Gobo patterns', 'Negative fill',
      // --- Stylistic & Dramatic ---
      'Cinematic Lighting', 'Film Noir', 'Dramatic Shadows', 'Low-Key', 'High-Key', 'Volumetric', 'God Rays', 'Crepuscular Rays', 'Backlight', 'Rim Light', 'Silhouette', 'Stormy lighting', 'Chiaroscuro', 'Tenebrism', 'Sidelight',
      // --- Technical & Camera Related ---
      'Anamorphic lens flare', 'Spherical lens flare', 'Long exposure light trails', 'Specular highlights', 'Diffuse reflection', 'Caustics from water', 'Refraction', 'Kelvin 3200K (Warm)', 'Kelvin 5500K (Daylight)', 'Kelvin 7500K (Cool)', 'High dynamic range (HDR)', 'Blown-out highlights', 'Crushed blacks',
      // --- Weather & Atmosphere ---
      'Lightning flash', 'Dense fog', 'Morning mist over a lake', 'Hazy summer afternoon', 'Sunbeams through clouds', 'Light pillar phenomenon', 'Light pollution from a city', 'Polluted city smog', 'Sandstorm', 'Blizzard', 'Tropical downpour', 'Volcanic ash cloud', 'Rainbow', 'Double rainbow', 'Fireflies at dusk',
      // --- Sci-Fi & Futuristic ---
      'Neon', 'Cyberpunk Neon Glow', 'Laser Grid', 'Strobe lights in a spaceship corridor', 'Plasma-core glow', 'Data stream light', 'Forcefield shimmer', 'Warp drive trail', 'Dyson sphere interior light', 'Engine thruster glow', 'Holographic projection light', 'Alien suns (binary, red giant)', 'Server room LED lights', 'Light from a futuristic UI', 'Quantum foam glimmer',
      // --- Fantasy & Mystical ---
      'Bioluminescence', 'Ethereal Glow', 'Magical Lighting', 'Divine light', 'Infernal glow', 'Eldritch glow', 'Aetherial glow', 'Light from a dragon\'s fire', 'Glimmering fairy dust', 'Necromantic green light', 'Light from a Paladin\'s hammer', 'Elven forest canopy light', 'Dwarven forge embers', 'Cursed artifact glow', 'Light from a magic portal', 'Ghostly apparition light', 'Light from a summoning circle', 'Crystal cavern luminescence', 'Enchanted weapon glow',
      // --- Environmental & Specific ---
      'Ambient light', 'Candlelight', 'Firelight', 'Bonfire light', 'Lantern light', 'Streetlights at night', 'Fairy lights', 'Underwater Lighting', 'Moody', 'Atmospheric', 'Car headlights on a wet road', 'TV screen glow', 'Smartphone screen light', 'Blacklight (UV)', 'Fireworks', 'Explosion flash', 'Muzzle flash', 'Sunlight through a stained-glass window', 'Light filtering through tree leaves', 'Light from a cracked door', 'Campfire stories lighting', 'Aquarium lighting', 'Museum exhibit lighting'
    ],
    lightDirections: [
      'Front', 'Directly from the front', 'Top-left', 'Top', 'Top-right', 'Left', 'Right', 'Slightly from the side', 'Bottom-left', 'Bottom', 'Bottom-right', 'From above', 'From a high angle', 'From below', 'From a low angle', 'Behind', 'Diffused from all around'
    ],
    artStyles: [
      // --- Core & Digital ---
      'Photorealistic', 'Illustration', '3D Render', 'Concept Art', 'Pixel Art', 'Vector Art', 'Octane Render', 'Unreal Engine', 'Vaporwave', 'Synthwave', 'Glitch Art', 'Low Poly', 'Isometric', 'Psychedelic Art',
      // --- Traditional Mediums ---
      'Watercolor', 'Oil Painting', 'Charcoal Sketch', 'Line Art', 'Doodle', 'Gouache', 'Ink Wash Painting (Sumi-e)', 'Acrylic Painting', 'Pastel Drawing', 'Colored Pencil', 'Woodcut Print',
      // --- Art Movements & Historical Styles ---
      'Surrealism', 'Impressionism', 'Pop Art', 'Art Nouveau', 'Art Deco', 'Cubism', 'Abstract', 'Minimalist', 'Ukiyo-e', 'Bauhaus', 'Brutalism', 'Graffiti', 'Futurism', 'Romanticism', 'Baroque',
      // --- Themed & Niche ---
      'Cyberpunk', 'Steampunk', 'Fantasy', 'Sci-Fi', 'Gothic', 'Film Noir', 'Vintage Photography', 'Comic Book Style', 'Blueprint Schematic', 'Technical Drawing', 'Sticker Art', 'Claymation', 'Stop Motion', 'Thermal Imaging', 'X-Ray Style', 'Solarpunk', 'Dieselpunk', 'Atompunk',
      // --- Game Franchises (AAA & AA) ---
      'The Legend of Zelda: Breath of the Wild style', 'Red Dead Redemption 2 style', 'Cyberpunk 2077 style', 'The Witcher 3 style', 'Elden Ring style', 'Dark Souls style', 'Bloodborne style', 'Final Fantasy VII Remake style', 'The Last of Us style', 'God of War (2018) style', 'Ghost of Tsushima style', 'Horizon Zero Dawn style', 'BioShock style', 'Mass Effect style', 'Skyrim style', 'Fallout style', 'Borderlands style', 'Overwatch style', 'Valorant style', 'League of Legends Splash Art', 'World of Warcraft style', 'Destiny 2 style', 'Assassin\'s Creed Valhalla style', 'Death Stranding style', 'Metal Gear Solid V style', 'Nier: Automata style',
      // --- Game Franchises (Stylized & Indie) ---
      'Persona 5 style', 'Genshin Impact Splash Art', 'Hades (game) style', 'Hollow Knight style', 'Ori and the Blind Forest style', 'Stardew Valley style', 'Animal Crossing style', 'Minecraft style', 'Cuphead style', 'Undertale style', 'Celeste style', 'Journey (game) style', 'Firewatch style', 'Gris style', 'Disco Elysium style', 'Life is Strange style', 'Okami style', 'Fortnite style', 'Sea of Thieves style',
      // --- Anime & Manga Series ---
      'Attack on Titan style', 'Demon Slayer: Kimetsu no Yaiba style', 'Jujutsu Kaisen style', 'My Hero Academia style', 'Naruto style', 'Dragon Ball Z (Akira Toriyama) style', 'One Piece (Eiichiro Oda) style', 'Bleach (Tite Kubo) style', 'Berserk (Kentaro Miura) style', 'Vagabond (Takehiko Inoue) style', 'JoJo\'s Bizarre Adventure style', 'Neon Genesis Evangelion style', 'Cowboy Bebop style', 'Akira (Katsuhiro Otomo) style', 'Ghost in the Shell style', 'Chainsaw Man style', 'Vinland Saga style', 'Made in Abyss style', 'Hunter x Hunter style', 'Mob Psycho 100 style', 'One-Punch Man style', 'Sailor Moon (90s) style',
      // --- Anime Directors & Studios ---
      'style of Studio Ghibli (Hayao Miyazaki)', 'style of Makoto Shinkai', 'style of Satoshi Kon', 'style of Mamoru Hosoda', 'style of Masaaki Yuasa', 'style of Studio Trigger', 'style of Ufotable', 'style of Kyoto Animation', 'style of Wit Studio', 'style of MAPPA',
      // --- Western Animation ---
      'Arcane (TV series) style', 'Spider-Man: Into the Spider-Verse style', 'Rick and Morty style', 'The Simpsons style', 'Adventure Time style', 'Gravity Falls style', 'Steven Universe style', 'Avatar: The Last Airbender style', 'The Dragon Prince style', 'Castlevania (Netflix series) style', 'Invincible (TV series) style', 'BoJack Horseman style', 'Clone Wars (2003) style', 'Samurai Jack style',
      // --- Animation Studios & Directors ---
      'style of Disney (Renaissance)', 'style of Pixar', 'style of DreamWorks', 'style of Laika (stop-motion)', 'style of Cartoon Saloon', 'style of Tim Burton',
      // --- Famous Artists ---
      'style of Alphonse Mucha', 'style of H.R. Giger', 'style of Greg Rutkowski', 'style of Moebius', 'style of Zdzisław Beksiński',
      // --- NEWLY ADDED STYLES ---
      'High Renaissance', 'Northern Renaissance', 'Mannerism', 'Neoclassicism', 'Realism', 'Pre-Raphaelite Brotherhood', 'Symbolism', 'Fauvism', 'Dadaism', 'Constructivism', 'De Stijl', 'Suprematism', 'Abstract Expressionism', 'Color Field Painting', 'Op Art', 'Kinetic Art', 'Fluxus', 'Post-Minimalism', 'Photorealism', 'Hyperrealism', 'Neo-Expressionism', 'Street Art', 'Lowbrow (Pop Surrealism)', 'Stuckism', 'Digital Art',
      'Fresco', 'Tempera painting', 'Encaustic painting', 'Sgraffito', 'Impasto', 'Pointillism', 'Divisionism', 'Tenebrism', 'Grisaille', 'Verdaccio', 'Cross-hatching', 'Stippling', 'Airbrushing', 'Digital Painting', 'Matte Painting', 'Photobashing', 'Kitbashing', 'Speedpainting',
      'Daguerreotype', 'Calotype', 'Tintype', 'Ambrotype', 'Albumen Print', 'Pictorialism', 'Straight Photography', 'Documentary Photography', 'Street Photography', 'Fashion Photography', 'Lomography', 'Polaroid photo', 'Infrared Photography', 'Black and White Infrared', 'High-Speed Photography', 'Light Painting', 'Double Exposure photography',
      'German Expressionist Cinema', 'Soviet Montage Theory', 'French New Wave', 'Italian Neorealism', 'Cinema Novo', 'Dogme 95', 'Technicolor Film', 'CinemaScope', 'VistaVision',
      'Ancient Egyptian Art', 'Greek and Roman Art', 'Byzantine Art', 'Romanesque Art', 'Gothic Architecture', 'Renaissance Architecture', 'Baroque Architecture', 'Rococo Architecture', 'Neoclassical Architecture', 'Beaux-Arts Architecture', 'Art Nouveau Architecture', 'Art Deco Architecture', 'International Style', 'Modernist Architecture', 'Postmodern Architecture', 'Deconstructivism', 'Brutalist Architecture', 'Googie Architecture', 'Sustainable Architecture',
      'Arts and Crafts Movement', 'Wiener Werkstätte', 'International Typographic Style (Swiss Style)', 'Psychedelic Design', 'Memphis Group Design', 'Flat Design', 'Skeuomorphism', 'Neumorphism', 'Glassmorphism',
      'Aboriginal Dot Painting', 'Celtic Knotwork', 'Islamic Geometric Patterns', 'Mayan Glyphs', 'Aztec Art', 'African Tribal Art', 'Haida Art', 'Maori Tattoo (Tā moko)', 'Russian Icon Painting', 'Byzantine Mosaics', 'Indian Miniature Painting', 'Persian Miniatures', 'Tibetan Thangka Painting', 'Chinese Calligraphy', 'Japanese Sumi-e',
      'Cottagecore', 'Goblincore', 'Dark Academia', 'Light Academia', 'Angelcore', 'Devilcore', 'Fairycore', 'Kidcore', 'Lovecore', 'Vintagecore', 'Webcore', 'Weirdcore', 'Traumacore', 'Dreamcore', 'Liminal Space aesthetic',
      'Botanical Illustration', 'Anatomical Drawing', 'Zoological Illustration', 'Architectural Blueprint', 'Engineering Schematics', 'Exploded-view drawing', 'Cutaway drawing',
      'Voxel Art', 'Toon Shading (Cel-Shading)', 'Wireframe model', 'ZBrush sculpting style', 'Procedural Generation art',
      'Terraria pixel art', 'Diablo 3 isometric dark fantasy', 'Path of Exile grimdark style', 'Starcraft 2 sci-fi RTS art', 'Dota 2 splash art', 'Hearthstone card art', 'Magic: The Gathering card art', 'Bayonetta stylish action style', 'Devil May Cry 5 photorealistic action', 'Resident Evil 8 survival horror realism', 'Silent Hill 2 psychological horror aesthetic', 'Yakuza (series) realistic urban Japan', 'Persona 3 style', 'Persona 4 style', 'Catherine (game) anime puzzle style', 'Dragon Quest (Akira Toriyama) style', 'Ni no Kuni Studio Ghibli style', 'Bravely Default storybook style', 'Octopath Traveler HD-2D style', 'Final Fantasy (Yoshitaka Amano) style', 'Kingdom Hearts (Tetsuya Nomura) style', 'Street Fighter V comic style', 'Guilty Gear Strive anime fighting game style', 'Mortal Kombat 11 dark realism', 'Apex Legends sci-fi concept art', 'The Outer Wilds stylized realism', 'No Man\'s Sky vibrant sci-fi', 'Limbo monochromatic style', 'Inside (game) 2.5D style', 'Little Nightmares grotesque style', 'Ori and the Will of the Wisps glowing forest style',
      'style of John Singer Sargent', 'style of William-Adolphe Bouguereau', 'style of Lawrence Alma-Tadema', 'style of J.M.W. Turner', 'style of Caspar David Friedrich', 'style of Gustave Doré', 'style of Ivan Aivazovsky', 'style of Ivan Shishkin', 'style of Ilya Repin', 'style of Wassily Kandinsky', 'style of Piet Mondrian', 'style of Kazimir Malevich', 'style of Salvador Dalí', 'style of René Magritte', 'style of Max Ernst', 'style of Joan Miró', 'style of Frida Kahlo', 'style of Georgia O\'Keeffe', 'style of Edward Hopper', 'style of Norman Rockwell', 'style of Andy Warhol', 'style of Roy Lichtenstein', 'style of Jean-Michel Basquiat', 'style of Keith Haring', 'style of Francis Bacon', 'style of Lucian Freud', 'style of David Hockney', 'style of Gerhard Richter', 'style of Anselm Kiefer', 'style of Yoshitaka Amano', 'style of Katsuya Terada', 'style of Yoji Shinkawa', 'style of Frank Frazetta', 'style of Boris Vallejo', 'style of Julie Bell', 'style of Drew Struzan', 'style of Ralph McQuarrie', 'style of Syd Mead', 'style of Chris Foss', 'style of John Harris', 'style of Sparth', 'style of Daniel Dociu', 'style of Feng Zhu', 'style of Craig Mullins', 'style of Ian McQue', 'style of Maciej Kuciara',
      '80s anime style', '90s anime style', '2000s anime style', 'Modern moe style', 'Isekai fantasy art', 'Shonen action manga style', 'Shojo romance manga style', 'Seinen dark manga style', 'Josei realistic manga style', 'Kodomomuke children\'s anime style', 'Mecha anime blueprint', 'Gekiga dramatic manga style',
      'Looney Tunes style', 'Hanna-Barbera style', 'Fleischer Studios rubber hose style', 'UPA (United Productions of America) style', 'Genndy Tartakovsky style (Samurai Jack, Primal)', 'Craig McCracken style (Powerpuff Girls)', 'Butch Hartman style (Fairly OddParents)', 'CalArts style', 'Archer (TV series) style', 'Bob\'s Burgers style', 'Invader Zim style'
    ],
    passportOutfits: [
      'White shirt & black vest', 'Dark suit with tie', 'Blouse with blazer', 'Collared polo shirt', 'Dark turtleneck sweater', 'Light-colored button-up shirt', 'Simple round-neck sweater', 'Professional scrub top (for medical fields)', 'Traditional Ao Dai (Vietnam)', 'Formal Kimono (Japan)', 'Sari Blouse (India)', 'Formal Barong Tagalog (Philippines)', 'Formal Hanbok (Korea)', 'Cheongsam top (China)'
    ],
    passportBackgrounds: [
      'White', 'Light Blue', 'Off-white', 'Grey', 'Dark Grey', 'Royal Blue', 'Neutral Beige', 'Cream', 'Solid Black (for specific uses)', 'Digital Gradient Blue'
    ]
  },
  vi: {
    lightingStyles: [
      // --- Cơ bản & Thời gian trong ngày ---
      'Ánh sáng tự nhiên', 'Giờ vàng', 'Giờ xanh', 'Trời u ám', 'Nắng trưa gay gắt', 'Bình minh', 'Hoàng hôn', 'Ánh trăng', 'Ánh sao', 'Ánh sáng buổi sáng sương mù', 'Nắng chiều', 'Chạng vạng',
      // --- Nhân tạo & Studio ---
      'Ánh sáng studio', 'Ánh sáng chính', 'Ánh sáng phụ', 'Chiếu sáng ba điểm', 'Ánh sáng Rembrandt', 'Ánh sáng bướm', 'Ánh sáng vòng lặp', 'Ánh sáng chia đôi', 'Ánh sáng dịu', 'Ánh sáng gắt', 'Đèn chiếu', 'Ánh sáng sân khấu', 'Đèn tròn', 'Đèn softbox', 'Ánh sáng cửa chuồng', 'Họa tiết Gobo', 'Bù sáng âm',
      // --- Phong cách & Kịch tính ---
      'Ánh sáng điện ảnh', 'Phim Noir', 'Bóng đổ kịch tính', 'Tối (Low-Key)', 'Sáng (High-Key)', 'Ánh sáng thể tích', 'Tia sáng của Chúa', 'Tia hoàng hôn', 'Ngược sáng', 'Ánh sáng viền', 'Bóng đen', 'Ánh sáng bão tố', 'Tương phản sáng tối (Chiaroscuro)', 'Chủ nghĩa Tenebrism', 'Ánh sáng bên',
      // --- Kỹ thuật & Liên quan đến Máy ảnh ---
      'Lóa ống kính Anamorphic', 'Lóa ống kính hình cầu', 'Vệt sáng phơi sáng dài', 'Điểm sáng phản chiếu', 'Phản xạ khuếch tán', 'Tụ quang từ nước', 'Khúc xạ', 'Nhiệt độ Kelvin 3200K (Ấm)', 'Nhiệt độ Kelvin 5500K (Ánh sáng ban ngày)', 'Nhiệt độ Kelvin 7500K (Mát)', 'Dải tương phản động mở rộng (HDR)', 'Cháy sáng', 'Mất chi tiết vùng tối',
      // --- Thời tiết & Khí quyển ---
      'Tia chớp', 'Sương mù dày đặc', 'Sương sớm trên mặt hồ', 'Buổi chiều mùa hè mờ ảo', 'Tia nắng qua mây', 'Hiện tượng cột sáng', 'Ô nhiễm ánh sáng từ thành phố', 'Khói bụi thành phố ô nhiễm', 'Bão cát', 'Bão tuyết', 'Mưa rào nhiệt đới', 'Đám mây tro núi lửa', 'Cầu vồng', 'Cầu vồng đôi', 'Đom đóm lúc chạng vạng',
      // --- Khoa học viễn tưởng & Tương lai ---
      'Đèn neon', 'Ánh sáng Neon Cyberpunk', 'Lưới laser', 'Đèn nhấp nháy trong hành lang tàu vũ trụ', 'Ánh sáng từ lõi plasma', 'Ánh sáng dòng dữ liệu', 'Ánh sáng lá chắn năng lượng', 'Vệt sáng khi dịch chuyển tức thời', 'Ánh sáng bên trong quả cầu Dyson', 'Ánh sáng từ động cơ đẩy', 'Ánh sáng từ hình chiếu голограф', 'Mặt trời ngoài hành tinh (hệ sao đôi, sao khổng lồ đỏ)', 'Đèn LED phòng máy chủ', 'Ánh sáng từ giao diện người dùng tương lai', 'Ánh sáng bọt lượng tử',
      // --- Kỳ ảo & Huyền bí ---
      'Phát quang sinh học', 'Ánh sáng thanh tao', 'Ánh sáng ma thuật', 'Ánh sáng thần thánh', 'Ánh sáng địa ngục', 'Ánh sáng kỳ quái', 'Ánh sáng cõi tiên', 'Ánh sáng từ lửa rồng', 'Bụi tiên lấp lánh', 'Ánh sáng xanh hắc ám', 'Ánh sáng từ búa của Paladin', 'Ánh sáng xuyên qua tán lá rừng tiên', 'Than hồng từ lò rèn người lùn', 'Ánh sáng từ cổ vật bị nguyền rủa', 'Ánh sáng từ cổng dịch chuyển ma thuật', 'Ánh sáng ma quái', 'Ánh sáng từ vòng tròn triệu hồi', 'Ánh sáng hang động pha lê', 'Vũ khí ma thuật phát sáng',
      // --- Môi trường & Cụ thể ---
      'Ánh sáng môi trường', 'Ánh nến', 'Ánh lửa', 'Ánh lửa trại', 'Ánh đèn lồng', 'Đèn đường ban đêm', 'Đèn dây tiên', 'Ánh sáng dưới nước', 'Tâm trạng', 'Khí quyển', 'Đèn pha ô tô trên đường ướt', 'Ánh sáng từ màn hình TV', 'Ánh sáng màn hình điện thoại', 'Đèn cực tím (UV)', 'Pháo hoa', 'Ánh sáng vụ nổ', 'Tia lửa đầu nòng', 'Ánh nắng qua cửa sổ kính màu', 'Ánh sáng xuyên qua kẽ lá', 'Ánh sáng từ khe cửa hé mở', 'Ánh sáng kể chuyện quanh lửa trại', 'Ánh sáng hồ cá', 'Ánh sáng trưng bày bảo tàng'
    ],
    lightDirections: [
      'Phía trước', 'Trực diện từ phía trước', 'Trên-trái', 'Phía trên', 'Trên-phải', 'Bên trái', 'Bên phải', 'Hơi từ bên cạnh', 'Dưới-trái', 'Phía dưới', 'Dưới-phải', 'Từ trên xuống', 'Từ góc cao', 'Từ dưới lên', 'Từ góc thấp', 'Phía sau', 'Khuếch tán từ mọi phía'
    ],
    artStyles: [
      // --- Cốt lõi & Kỹ thuật số ---
      'Như ảnh chụp', 'Minh họa', 'Kết xuất 3D', 'Nghệ thuật ý tưởng', 'Nghệ thuật Pixel', 'Nghệ thuật Vector', 'Kết xuất Octane', 'Unreal Engine', 'Vaporwave', 'Synthwave', 'Nghệ thuật Glitch', 'Đa giác thấp (Low Poly)', 'Phối cảnh Isometic', 'Nghệ thuật ảo giác',
      // --- Phương tiện Truyền thống ---
      'Màu nước', 'Sơn dầu', 'Phác thảo than', 'Nét vẽ', 'Vẽ nguệch ngoạc', 'Sơn Gouache', 'Tranh thủy mặc (Sumi-e)', 'Sơn Acrylic', 'Vẽ phấn tiên', 'Bút chì màu', 'In khắc gỗ',
      // --- Trường phái & Phong cách Lịch sử ---
      'Chủ nghĩa siêu thực', 'Chủ nghĩa ấn tượng', 'Nghệ thuật Pop', 'Art Nouveau', 'Art Deco', 'Chủ nghĩa lập thể', 'Trừu tượng', 'Tối giản', 'Ukiyo-e (Tranh khắc gỗ Nhật Bản)', 'Phong cách Bauhaus', 'Chủ nghĩa Thô mộc', 'Graffiti', 'Chủ nghĩa vị lai', 'Chủ nghĩa lãng mạn', 'Phong cách Baroque',
      // --- Theo chủ đề & Niche ---
      'Cyberpunk', 'Steampunk', 'Kỳ ảo', 'Khoa học viễn tưởng', 'Gothic', 'Phim Noir', 'Nhiếp ảnh cổ điển', 'Phong cách truyện tranh', 'Sơ đồ bản thiết kế', 'Bản vẽ kỹ thuật', 'Nghệ thuật Sticker', 'Hoạt hình đất sét', 'Hoạt hình tĩnh vật', 'Ảnh nhiệt', 'Phong cách X-quang', 'Solarpunk', 'Dieselpunk', 'Atompunk',
      // --- Thương hiệu Game (AAA & AA) ---
      'Phong cách The Legend of Zelda: Breath of the Wild', 'Phong cách Red Dead Redemption 2', 'Phong cách Cyberpunk 2077', 'Phong cách The Witcher 3', 'Phong cách Elden Ring', 'Phong cách Dark Souls', 'Phong cách Bloodborne', 'Phong cách Final Fantasy VII Remake', 'Phong cách The Last of Us', 'Phong cách God of War (2018)', 'Phong cách Ghost of Tsushima', 'Phong cách Horizon Zero Dawn', 'Phong cách BioShock', 'Phong cách Mass Effect', 'Phong cách Skyrim', 'Phong cách Fallout', 'Phong cách Borderlands', 'Phong cách Overwatch', 'Phong cách Valorant', 'Tranh Splash Art của League of Legends', 'Phong cách World of Warcraft', 'Phong cách Destiny 2', 'Phong cách Assassin\'s Creed Valhalla', 'Phong cách Death Stranding', 'Phong cách Metal Gear Solid V', 'Phong cách Nier: Automata',
      // --- Thương hiệu Game (Cách điệu & Indie) ---
      'Phong cách Persona 5', 'Tranh Splash Art của Genshin Impact', 'Phong cách Hades (game)', 'Phong cách Hollow Knight', 'Phong cách Ori and the Blind Forest', 'Phong cách Stardew Valley', 'Phong cách Animal Crossing', 'Phong cách Minecraft', 'Phong cách Cuphead', 'Phong cách Undertale', 'Phong cách Celeste', 'Phong cách Journey (game)', 'Phong cách Firewatch', 'Phong cách Gris', 'Phong cách Disco Elysium', 'Phong cách Life is Strange', 'Phong cách Okami', 'Phong cách Fortnite', 'Phong cách Sea of Thieves',
      // --- Series Anime & Manga ---
      'Phong cách Attack on Titan', 'Phong cách Demon Slayer: Kimetsu no Yaiba', 'Phong cách Jujutsu Kaisen', 'Phong cách My Hero Academia', 'Phong cách Naruto', 'Phong cách Dragon Ball Z (Akira Toriyama)', 'Phong cách One Piece (Eiichiro Oda)', 'Phong cách Bleach (Tite Kubo)', 'Phong cách Berserk (Kentaro Miura)', 'Phong cách Vagabond (Takehiko Inoue)', 'Phong cách JoJo\'s Bizarre Adventure', 'Phong cách Neon Genesis Evangelion', 'Phong cách Cowboy Bebop', 'Phong cách Akira (Katsuhiro Otomo)', 'Phong cách Ghost in the Shell', 'Phong cách Chainsaw Man', 'Phong cách Vinland Saga', 'Phong cách Made in Abyss', 'Phong cách Hunter x Hunter', 'Phong cách Mob Psycho 100', 'Phong cách One-Punch Man', 'Phong cách Sailor Moon (thập niên 90)',
      // --- Đạo diễn & Studio Anime ---
      'phong cách của Studio Ghibli (Hayao Miyazaki)', 'phong cách của Makoto Shinkai', 'phong cách của Satoshi Kon', 'phong cách của Mamoru Hosoda', 'phong cách của Masaaki Yuasa', 'phong cách của Studio Trigger', 'phong cách của Ufotable', 'phong cách của Kyoto Animation', 'phong cách của Wit Studio', 'phong cách của MAPPA',
      // --- Hoạt hình phương Tây ---
      'Phong cách Arcane (series)', 'Phong cách Spider-Man: Into the Spider-Verse', 'Phong cách Rick and Morty', 'Phong cách The Simpsons', 'Phong cách Adventure Time', 'Phong cách Gravity Falls', 'Phong cách Steven Universe', 'Phong cách Avatar: The Last Airbender', 'Phong cách The Dragon Prince', 'Phong cách Castlevania (series Netflix)', 'Phong cách Invincible (series)', 'Phong cách BoJack Horseman', 'Phong cách Clone Wars (2003)', 'Phong cách Samurai Jack',
      // --- Studio & Đạo diễn Hoạt hình ---
      'phong cách của Disney (thời kỳ Phục hưng)', 'phong cách của Pixar', 'phong cách của DreamWorks', 'phong cách của Laika (hoạt hình tĩnh vật)', 'phong cách của Cartoon Saloon', 'phong cách của Tim Burton',
      // --- Họa sĩ Nổi tiếng ---
      'phong cách của Alphonse Mucha', 'phong cách của H.R. Giger', 'phong cách của Greg Rutkowski', 'phong cách của Moebius', 'phong cách của Zdzisław Beksiński',
      // --- PHONG CÁCH MỚI ĐƯỢC THÊM ---
      'Phục Hưng Cao Trào', 'Phục Hưng phương Bắc', 'Trường phái Kiểu cách', 'Tân cổ điển', 'Chủ nghĩa Hiện thực', 'Hội Anh em Tiền Raphael', 'Chủ nghĩa Tượng trưng', 'Chủ nghĩa Dã thú', 'Chủ nghĩa Dada', 'Chủ nghĩa Kiến tạo', 'Phong cách De Stijl', 'Chủ nghĩa Tối cao', 'Chủ nghĩa Biểu hiện Trừu tượng', 'Hội họa Trường phái Màu sắc', 'Nghệ thuật Op', 'Nghệ thuật Động học', 'Trào lưu Fluxus', 'Chủ nghĩa Hậu Tối giản', 'Chủ nghĩa Ảnh thực', 'Chủ nghĩa Siêu thực', 'Tân Biểu hiện', 'Nghệ thuật đường phố', 'Nghệ thuật Lowbrow (Siêu thực Pop)', 'Chủ nghĩa Stuckism', 'Nghệ thuật số',
      'Vẽ Fresco', 'Hội họa Tempera', 'Hội họa Encaustic', 'Kỹ thuật Sgraffito', 'Kỹ thuật Impasto', 'Chủ nghĩa Điểm họa', 'Chủ nghĩa Phân điểm', 'Chủ nghĩa Tenebrism', 'Kỹ thuật Grisaille', 'Kỹ thuật Verdaccio', 'Đan chéo nét', 'Chấm Stippling', 'Vẽ Airbrush', 'Vẽ kỹ thuật số', 'Vẽ Matte Painting', 'Photobashing', 'Kitbashing', 'Vẽ nhanh (Speedpainting)',
      'Thuật chụp Daguerre', 'Thuật chụp Calotype', 'Thuật chụp Tintype', 'Thuật chụp Ambrotype', 'In ảnh Albumen', 'Trường phái Nhiếp ảnh Nghệ thuật', 'Nhiếp ảnh Thuần túy', 'Nhiếp ảnh tài liệu', 'Nhiếp ảnh đường phố', 'Nhiếp ảnh thời trang', 'Chụp ảnh Lomo', 'Ảnh Polaroid', 'Nhiếp ảnh hồng ngoại', 'Hồng ngoại đen trắng', 'Nhiếp ảnh tốc độ cao', 'Vẽ tranh bằng ánh sáng', 'Chồng ảnh (nhiếp ảnh)',
      'Điện ảnh Biểu hiện Đức', 'Lý thuyết Dựng phim Xô Viết', 'Làn sóng Mới của Pháp', 'Chủ nghĩa Tân hiện thực Ý', 'Trào lưu Cinema Novo', 'Trào lưu Dogme 95', 'Phim Technicolor', 'Định dạng CinemaScope', 'Định dạng VistaVision',
      'Nghệ thuật Ai Cập Cổ đại', 'Nghệ thuật Hy Lạp và La Mã', 'Nghệ thuật Byzantine', 'Nghệ thuật Romanesque', 'Kiến trúc Gothic', 'Kiến trúc Phục Hưng', 'Kiến trúc Baroque', 'Kiến trúc Rococo', 'Kiến trúc Tân cổ điển', 'Kiến trúc Beaux-Arts', 'Kiến trúc Art Nouveau', 'Kiến trúc Art Deco', 'Phong cách Quốc tế', 'Kiến trúc Hiện đại', 'Kiến trúc Hậu Hiện đại', 'Chủ nghĩa Giải tỏa kết cấu', 'Kiến trúc Thô mộc', 'Kiến trúc Googie', 'Kiến trúc Bền vững',
      'Phong trào Nghệ thuật và Thủ công', 'Trường phái Wiener Werkstätte', 'Phong cách Thụy Sĩ (Kiểu chữ Quốc tế)', 'Thiết kế Ảo giác', 'Nhóm thiết kế Memphis', 'Thiết kế phẳng', 'Mô phỏng (Skeuomorphism)', 'Tân mô phỏng (Neumorphism)', 'Chủ nghĩa Thủy tinh (Glassmorphism)',
      'Hội họa chấm của thổ dân Úc', 'Nút thắt Celtic', 'Họa tiết hình học Hồi giáo', 'Chữ tượng hình Maya', 'Nghệ thuật Aztec', 'Nghệ thuật bộ lạc châu Phi', 'Nghệ thuật Haida', 'Hình xăm Maori (Tā moko)', 'Hội họa biểu tượng Nga', 'Tranh ghép Byzantine', 'Tranh tiểu họa Ấn Độ', 'Tranh tiểu họa Ba Tư', 'Tranh Thangka Tây Tạng', 'Thư pháp Trung Quốc', 'Tranh thủy mặc Nhật Bản (Sumi-e)',
      'Thẩm mỹ Cottagecore', 'Thẩm mỹ Goblincore', 'Thẩm mỹ Dark Academia', 'Thẩm mỹ Light Academia', 'Thẩm mỹ Angelcore', 'Thẩm mỹ Devilcore', 'Thẩm mỹ Fairycore', 'Thẩm mỹ Kidcore', 'Thẩm mỹ Lovecore', 'Thẩm mỹ Vintagecore', 'Thẩm mỹ Webcore', 'Thẩm mỹ Weirdcore', 'Thẩm mỹ Traumacore', 'Thẩm mỹ Dreamcore', 'Không gian Liminal',
      'Minh họa thực vật', 'Vẽ giải phẫu', 'Minh họa động vật học', 'Bản thiết kế kiến trúc', 'Sơ đồ kỹ thuật', 'Bản vẽ chi tiết', 'Bản vẽ cắt lớp',
      'Nghệ thuật Voxel', 'Đổ bóng Toon (Cel-Shading)', 'Mô hình khung dây', 'Phong cách điêu khắc ZBrush', 'Nghệ thuật tạo sinh',
      'Pixel art của Terraria', 'Fantasy tối isometric của Diablo 3', 'Phong cách u ám của Path of Exile', 'Nghệ thuật RTS khoa học viễn tưởng của Starcraft 2', 'Splash art của Dota 2', 'Nghệ thuật thẻ bài Hearthstone', 'Nghệ thuật thẻ bài Magic: The Gathering', 'Phong cách hành động của Bayonetta', 'Hành động chân thực của Devil May Cry 5', 'Chủ nghĩa hiện thực kinh dị sinh tồn của Resident Evil 8', 'Thẩm mỹ kinh dị tâm lý của Silent Hill 2', 'Đô thị Nhật Bản thực tế của series Yakuza', 'Phong cách UI anime của Persona 3', 'Phong cách UI anime của Persona 4', 'Phong cách giải đố anime của Catherine (game)', 'Phong cách Dragon Quest (Akira Toriyama)', 'Phong cách Ni no Kuni Studio Ghibli', 'Phong cách sách truyện của Bravely Default', 'Phong cách HD-2D của Octopath Traveler', 'Phong cách Final Fantasy (Yoshitaka Amano)', 'Phong cách Kingdom Hearts (Tetsuya Nomura)', 'Phong cách truyện tranh của Street Fighter V', 'Phong cách game đối kháng anime của Guilty Gear Strive', 'Chủ nghĩa hiện thực tăm tối của Mortal Kombat 11', 'Nghệ thuật ý tưởng khoa học viễn tưởng của Apex Legends', 'Chủ nghĩa hiện thực cách điệu của The Outer Wilds', 'Khoa học viễn tưởng rực rỡ của No Man\'s Sky', 'Phong cách đơn sắc của Limbo', 'Phong cách 2.5D của Inside (game)', 'Phong cách kỳ괴 của Little Nightmares', 'Phong cách rừng phát sáng của Ori and the Will of the Wisps',
      'phong cách của John Singer Sargent', 'phong cách của William-Adolphe Bouguereau', 'phong cách của Lawrence Alma-Tadema', 'phong cách của J.M.W. Turner', 'phong cách của Caspar David Friedrich', 'phong cách của Gustave Doré', 'phong cách của Ivan Aivazovsky', 'phong cách của Ivan Shishkin', 'phong cách của Ilya Repin', 'phong cách của Wassily Kandinsky', 'phong cách của Piet Mondrian', 'phong cách của Kazimir Malevich', 'phong cách của Salvador Dalí', 'phong cách của René Magritte', 'phong cách của Max Ernst', 'phong cách của Joan Miró', 'phong cách của Frida Kahlo', 'phong cách của Georgia O\'Keeffe', 'phong cách của Edward Hopper', 'phong cách của Norman Rockwell', 'phong cách của Andy Warhol', 'phong cách của Roy Lichtenstein', 'phong cách của Jean-Michel Basquiat', 'phong cách của Keith Haring', 'phong cách của Francis Bacon', 'phong cách của Lucian Freud', 'phong cách của David Hockney', 'phong cách của Gerhard Richter', 'phong cách của Anselm Kiefer', 'phong cách của Yoshitaka Amano', 'phong cách của Katsuya Terada', 'phong cách của Yoji Shinkawa', 'phong cách của Frank Frazetta', 'phong cách của Boris Vallejo', 'phong cách của Julie Bell', 'phong cách của Drew Struzan', 'phong cách của Ralph McQuarrie', 'phong cách của Syd Mead', 'phong cách của Chris Foss', 'phong cách của John Harris', 'phong cách của Sparth', 'phong cách của Daniel Dociu', 'phong cách của Feng Zhu', 'phong cách của Craig Mullins', 'phong cách của Ian McQue', 'phong cách của Maciej Kuciara',
      'Phong cách anime thập niên 80', 'Phong cách anime thập niên 90', 'Phong cách anime 2000s', 'Phong cách moe hiện đại', 'Nghệ thuật fantasy Isekai', 'Phong cách manga hành động Shonen', 'Phong cách manga lãng mạn Shojo', 'Phong cách manga tăm tối Seinen', 'Phong cách manga thực tế Josei', 'Phong cách anime trẻ em Kodomomuke', 'Bản thiết kế anime Mecha', 'Phong cách manga kịch Gekiga',
      'Phong cách Looney Tunes', 'Phong cách Hanna-Barbera', 'Phong cách hoạt hình ống cao su của Fleischer Studios', 'Phong cách UPA (United Productions of America)', 'Phong cách Genndy Tartakovsky (Samurai Jack, Primal)', 'Phong cách Craig McCracken (Powerpuff Girls)', 'Phong cách Butch Hartman (Fairly OddParents)', 'Phong cách CalArts', 'Phong cách Archer (series)', 'Phong cách Bob\'s Burgers', 'Phong cách Invader Zim'
    ],
    passportOutfits: [
      'Áo sơ mi trắng & vest đen', 'Vest tối màu có cà vạt', 'Áo kiểu với áo khoác blazer', 'Áo polo có cổ', 'Áo len cổ lọ tối màu', 'Áo sơ mi cài cúc sáng màu', 'Áo len cổ tròn đơn giản', 'Áo blouse chuyên dụng (cho ngành y)', 'Áo dài truyền thống (Việt Nam)', 'Kimono trang trọng (Nhật Bản)', 'Áo Sari (Ấn Độ)', 'Áo Barong Tagalog trang trọng (Philippines)', 'Hanbok trang trọng (Hàn Quốc)', 'Áo sườn xám (Trung Quốc)'
    ],
    passportBackgrounds: [
      'Trắng', 'Xanh nhạt', 'Trắng ngà', 'Xám', 'Xám đậm', 'Xanh dương đậm', 'Màu be trung tính', 'Màu kem', 'Đen trơn (cho mục đích cụ thể)', 'Xanh dương chuyển sắc kỹ thuật số'
    ]
  }
};