export const promptTags = {
    styleCategory: [
        'Photorealistic', 'Illustration', 'Anime', 'Manga', '3D Render', 'Concept Art', 'Pixel Art',
        'Abstract', 'Futuristic', 'Cyberpunk', 'Steampunk', 'Vintage', 'Retro', '80s', '90s',
        'Minimalist', 'Art Deco', 'Art Nouveau', 'Surrealism', 'Impressionism', 'Expressionism',
        'Ukiyo-e', 'Watercolor', 'Oil painting', 'Charcoal sketch', 'Line art', 'Doodle', 'Sticker art',
        'Graffiti', 'Low poly', 'Isometric', 'Vaporwave', 'Glitch art', 'Psychedelic', 'Gothic',
        'Baroque', 'Rococo', 'Neoclassicism', 'Romanticism', 'Realism', 'Cubism', 'Fauvism', 'Pop Art',
        'Abstract Expressionism', 'Fantasy', 'Sci-Fi', 'Horror', 'Noir', 'Western', 'Dieselpunk',
        'Biopunk', 'Nanopunk', 'Mythological', 'Tribal', 'Cel-shaded', 'Collage', 'Blueprint',
        'Bauhaus', 'Pointillism', 'Synthwave', 'Brutalism', 'Lovecraftian', 'Solarpunk', 'Cartoon',
        'Comic book style', 'Dadaism', 'Memphis Design', 'Sovietwave', 'Atompunk', 'Infographic',
        'style of Alphonse Mucha', 'style of H.R. Giger', 'style of Moebius', 'style of Greg Rutkowski',
        'style of Zdzisław Beksiński', 'style of James Gurney', 'style of Hayao Miyazaki', 'style of Banksy',
        'style of Syd Mead', 'style of John Berkey', 'style of Katsuhiro Otomo', 'style of Rembrandt', 'style of Caravaggio'
    ],
    qualityCategory: [
        'Masterpiece', 'Best quality', '4K', '8K', 'UHD', 'Ultra realistic', 'Highly detailed',
        'Intricate details', 'Sharp focus', 'Professionally shot', 'Cinematic', 'Photorealistic',
        'High resolution', 'Flawless', 'Award-winning', 'Breathtaking', 'Epic', 'Stunning',
        'Insanely detailed', 'Octane render', 'Unreal Engine 5', 'V-Ray', 'Arnold render',
        'Physically-based rendering (PBR)', 'Global illumination', 'Ray tracing', 'Subsurface scattering',
        'Anisotropic filtering', 'Texture mapping', 'Hyper-detailed', 'Super resolution', 'Crisp details',
        'Fine details', 'Detailed face', 'Detailed eyes', 'Detailed background', 'Perfect composition',
        'Museum quality', 'Exquisite detail', 'Professional color grading', 'Canon EOS R5', 'Sony A7R IV',
        'High dynamic range (HDR)', 'Textured', 'Smooth', 'Clean', 'Flawless', 'Perfect anatomy',
        'Perfect hands', 'Accurate', 'Physically accurate', 'ISO 50', 'ISO 100', 'Low noise',
        'Artifact-free', 'Depth of Field (DoF)', 'Trending on ArtStation', 'Flickr', '500px', 'Behance',
        'Fuji Velvia', 'Kodak Portra 400', 'Ilford HP5', 'Cinestill 800T'
    ],
    lightingCategory: [
        'Cinematic lighting', 'Dramatic lighting', 'Volumetric lighting', 'God rays', 'Crepuscular rays', 'Rim light', 'Backlight', 'Silhouette',
        'Golden hour', 'Blue hour', 'Dawn', 'Dusk', 'Midday sun', 'Night', 'Overcast',
        'Soft light', 'Hard light', 'Studio lighting', 'Three-point lighting', 'Rembrandt lighting', 'Low-key', 'High-key',
        'Neon lights', 'Cyberpunk lighting', 'Bioluminescence', 'Glowing', 'Iridescent', 'Holographic',
        'Natural light', 'Sunlight', 'Moonlight', 'Starlight', 'Candlelight', 'Firelight', 'Lantern light',
        'Eerie lighting', 'Magical lighting', 'Atmospheric lighting', 'Moody lighting', 'Chiaroscuro',
        'Foggy', 'Hazy', 'Misty', 'Underwater lighting', 'Northern lights (Aurora Borealis)', 'Laser lights', 'Stage lighting', 'Spotlight',
        'Street lights', 'Caustics', 'Light shafts', 'Flickering light', 'Pulsating light', 'Subsurface scattering'
    ],
    colorCategory: [
        'Vibrant colors', 'Monochromatic', 'Pastel colors', 'Black and white', 'Complementary colors',
        'Analogous colors', 'Triadic colors', 'Neon palette', 'Warm color palette', 'Cool color palette',
        'Tones of blue', 'Tones of red', 'Sepia', 'Duotone', 'Tritone', 'Polychromatic', 'Iridescent',
        'Holographic', 'Technicolor', 'Muted colors', 'Earth tones', 'Jewel tones', 'Saturated',
        'Desaturated', 'High contrast', 'Low contrast', 'Color grading', 'Cinematic color palette',
        'Vintage film colors', 'Gradient', 'Rainbow', 'Spectrum', 'Psychedelic colors', 'Ethereal colors',
        'Dark and moody colors', 'Bright and cheerful colors', 'Electric colors', 'Metallic colors',
        'Gold', 'Silver', 'Copper', 'Bronze', 'Rich colors', 'Deep colors', 'Light colors', 'Faded colors',
        'Color splash', 'Selective color', 'Harmonious colors', 'Infernal palette', 'Celestial palette',
        'Tangerine and cyan', 'Synthwave palette', 'Acid colors'
    ],
    compositionCategory: [
        'Wide-angle shot', 'Close-up shot', 'Extreme close-up', 'Full body shot', 'Portrait',
        'Landscape', 'Dutch angle', 'Low angle', 'High angle', 'Birds-eye view', 'Worms-eye view',
        'Bokeh', 'Shallow depth of field', 'Deep depth of field', 'Rule of thirds', 'Leading lines',
        'Symmetry', 'Asymmetry', 'Dynamic composition', 'Centered composition', 'Off-center composition',
        'Fisheye lens', 'Macro shot', 'Telephoto shot', 'Pan shot', 'Tilt shot', 'Crane shot', 'Dolly zoom',
        'Over-the-shoulder shot', 'Point-of-view (POV)', 'Golden ratio', 'Frame within a frame',
        'Negative space', 'Headshot', 'Bust shot', 'Cowboy shot', 'Establishing shot', 'Tilted frame',
        '24mm lens', '35mm lens', '50mm lens', '85mm lens', '135mm lens', '200mm lens', 'Forced perspective', 'Panoramic',
        'Long shot', 'Medium shot', 'Diagonal composition', 'Drone shot', 'GoPro view', 'Found footage',
        'Unconventional framing', 'Flat lay', 'Ken Burns effect', 'Snorricam shot', 'Tilt-shift photography'
    ],
    effectsCategory: [
        'Lens flare', 'Glow', 'God rays', 'Chromatic aberration', 'Motion blur', 'Anamorphic', 'Light trails',
        'Particle effects', 'Sparks', 'Smoke', 'Fog', 'Haze', 'Mist', 'Rain', 'Snow', 'Drizzle',
        'Dust particles', 'Film grain', 'Vignette', 'Light leaks', 'Bloom', 'Glitch effect', 'Scanlines',
        'VHS effect', 'Pixelation', 'Halftone', 'Double exposure', 'Long exposure', 'Time-lapse',
        'Water ripples', 'Fire embers', 'Electrical arcs', 'Magic spells', 'Energy blasts', 'Force field',
        'Distortion', 'Heat haze', 'Atmospheric scattering', 'Dreamlike', 'Ethereal', 'Explosion',
        'Fireworks', 'Water splash', 'Bubbles', 'Confetti', 'Shimmering', 'Floating particles', 'Aura',
        'Energy shield', 'Time distortion', 'Data stream', 'Fractal patterns', 'Liquify', 'Lensbaby effect'
    ],
    subjectPoseCategory: [
        'Standing', 'Sitting', 'Lying down', 'Running', 'Jumping', 'Walking', 'Looking at viewer',
        'Looking away', 'Action pose', 'Dynamic pose', 'Relaxed pose', 'Contemplative', 'Serene',
        'Triumphant', 'Defeated', 'Crouching', 'Leaning', 'Stretching', 'Dancing', 'Fighting',
        'Meditating', 'Praying', 'Reaching out', 'Arms crossed', 'Hands on hips', 'Profile view',
        'Three-quarter view', 'Back view', 'In motion', 'Mid-air', 'Floating', 'Swimming', 'Kneeling',
        'Bowing', 'Waving', 'Pointing', 'Shouting', 'Whispering', 'Laughing', 'Crying', 'Smirking',
        'Frowning', 'Defensive stance', 'Offensive stance', 'Elegant pose', 'Powerful stance',
        'Hiding', 'Peeking', 'Cowering', 'Gazing at the stars', 'Leaping through the air', 'Defiant stance',
        'Summoning', 'Conducting magic', 'Holding a glowing orb', 'Unsheathing a sword'
    ],
    outfitCategory: [
        'Casual wear', 'Formal suit', 'Ball gown', 'Sci-fi armor', 'Fantasy armor', 'Kimono', 'Hoodie',
        'Leather jacket', 'Vintage dress', 'Steampunk attire', 'Cyberpunk clothing', 'Military uniform',
        'Spacesuit', 'Traditional robes', 'Victorian dress', 'Gothic lolita', 'Punk rock outfit',
        'Business attire', 'Wedding dress', 'Lab coat', 'Magical girl outfit', 'Knight armor',
        'Samurai armor', 'Viking gear', 'Post-apocalyptic rags', 'Adventurer\'s gear', 'Royal garments',
        'Peasant clothes', 'Worn and torn', 'Clean and pristine', 'Elaborate headdress', 'Flowing cape',
        'Cloak with hood', 'Heavy boots', 'Elegant gloves', 'Intricate jewelry', 'Gas mask', 'Goggles',
        'Crown', 'Tiara', 'Ribbons', 'Lace', 'Denim', 'Trench coat', 'Superhero costume', 'Festival attire',
        'Bio-mechanical suit', 'Exosuit', 'Ornate filigree armor', 'Glowing runes', 'Power armor'
    ],
    environmentCategory: [
        'Forest', 'Jungle', 'Desert', 'Mountains', 'Ocean', 'Beach', 'Cityscape', 'Futuristic city',
        'Ruined city', 'Underwater city', 'Alien planet', 'Volcano', 'Cave', 'Castle', 'Temple',
        'Spaceship interior', 'Cyberpunk alley', 'Steampunk workshop', 'Magical library',
        'Enchanted forest', 'Apocalyptic wasteland', 'Barren plains', 'Arctic tundra', 'Swamp',
        'Meadow', 'Floating islands', 'Crystal cavern', 'Inside a giant machine', 'On the moon',
        'In deep space', 'Surreal landscape', 'Dreamscape', 'Hellscape', 'Heavenly realm',
        'Glacial landscape', 'Skyscraper rooftop', 'Cozy cottage', 'Bustling market', 'Abandoned factory',
        'Throne room', 'Ballroom', 'Spaceship bridge', 'Bioluminescent forest', 'Corrupted landscape',
        'Sakura garden', 'Bamboo forest', 'City on clouds', 'Interdimensional library', 'Dyson sphere',
        'Ringworld', 'Galactic nebula', 'Post-human Earth', 'Solarpunk city'
    ],
    materialsCategory: [
        'Metal', 'Wood', 'Stone', 'Glass', 'Fabric', 'Leather', 'Plastic', 'Rubber', 'Silk', 'Velvet',
        'Cotton', 'Wool', 'Fur', 'Scales', 'Feathers', 'Bone', 'Crystal', 'Gemstone', 'Marble', 'Granite',
        'Concrete', 'Brick', 'Chrome', 'Gold', 'Silver', 'Bronze', 'Copper', 'Rusted metal',
        'Polished metal', 'Matte finish', 'Glossy finish', 'Translucent', 'Opaque', 'Glowing material',
        'Holographic material', 'Liquid metal', 'Organic texture', 'Rough texture', 'Smooth texture',
        'Woven texture', 'Engraved details', 'Filigree', 'Damascus steel', 'Carbon fiber', 'Obsidian',
        'Jade', 'Amber', 'Porcelain', 'Stained glass', 'Circuitry patterns', 'Lava', 'Ice',
        'Liquid crystal', 'Iridescent scales', 'Woven carbon fiber', 'Chiseled obsidian', 'Bioluminescent fungi'
    ],
};