export const promptTags = {
    styleCategory: [
        'Như ảnh chụp', 'Minh họa', 'Anime', 'Manga', 'Kết xuất 3D', 'Nghệ thuật ý tưởng', 'Nghệ thuật Pixel',
        'Trừu tượng', 'Tương lai', 'Cyberpunk', 'Steampunk', 'Cổ điển', 'Retro', 'Thập niên 80', 'Thập niên 90',
        'Tối giản', 'Art Deco', 'Art Nouveau', 'Chủ nghĩa siêu thực', 'Chủ nghĩa ấn tượng', 'Chủ nghĩa biểu hiện',
        'Ukiyo-e', 'Màu nước', 'Sơn dầu', 'Phác thảo than', 'Nét vẽ', 'Vẽ nguệch ngoạc', 'Nghệ thuật sticker',
        'Graffiti', 'Low poly', 'Isometric', 'Vaporwave', 'Nghệ thuật Glitch', 'Ảo giác', 'Gothic',
        'Baroque', 'Rococo', 'Tân cổ điển', 'Chủ nghĩa lãng mạn', 'Chủ nghĩa hiện thực', 'Chủ nghĩa lập thể', 'Chủ nghĩa dã thú', 'Nghệ thuật Pop',
        'Chủ nghĩa biểu hiện trừu tượng', 'Kỳ ảo', 'Khoa học viễn tưởng', 'Kinh dị', 'Noir', 'Miền Tây', 'Dieselpunk',
        'Biopunk', 'Nanopunk', 'Thần thoại', 'Bộ lạc', 'Cel-shaded', 'Ảnh ghép', 'Bản thiết kế',
        'Bauhaus', 'Chủ nghĩa điểm họa', 'Synthwave', 'Chủ nghĩa thô mộc', 'Kinh dị Lovecraft', 'Solarpunk', 'Hoạt hình',
        'Phong cách truyện tranh', 'Chủ nghĩa Dada', 'Thiết kế Memphis', 'Sovietwave', 'Atompunk', 'Đồ họa thông tin',
        'phong cách của Alphonse Mucha', 'phong cách của H.R. Giger', 'phong cách của Moebius', 'phong cách của Greg Rutkowski',
        'phong cách của Zdzisław Beksiński', 'phong cách của James Gurney', 'phong cách của Hayao Miyazaki', 'phong cách của Banksy',
        'phong cách của Syd Mead', 'phong cách của John Berkey', 'phong cách của Katsuhiro Otomo', 'phong cách của Rembrandt', 'phong cách của Caravaggio'
    ],
    qualityCategory: [
        'Tuyệt tác', 'Chất lượng tốt nhất', '4K', '8K', 'UHD', 'Siêu thực', 'Chi tiết cao',
        'Chi tiết tinh xảo', 'Lấy nét sắc nét', 'Chụp chuyên nghiệp', 'Điện ảnh', 'Như ảnh chụp',
        'Độ phân giải cao', 'Hoàn hảo', 'Đoạt giải thưởng', 'Ngoạn mục', 'Sử thi', 'Lộng lẫy',
        'Chi tiết đến kinh ngạc', 'Kết xuất Octane', 'Unreal Engine 5', 'V-Ray', 'Kết xuất Arnold',
        'Kết xuất dựa trên vật lý (PBR)', 'Chiếu sáng toàn cục', 'Dò tia', 'Tán xạ dưới bề mặt',
        'Lọc bất đẳng hướng', 'Ánh xạ họa tiết', 'Siêu chi tiết', 'Siêu phân giải', 'Chi tiết sắc nét',
        'Chi tiết tinh vi', 'Khuôn mặt chi tiết', 'Đôi mắt chi tiết', 'Nền chi tiết', 'Bố cục hoàn hảo',
        'Chất lượng bảo tàng', 'Chi tiết tinh tế', 'Chỉnh màu chuyên nghiệp', 'Canon EOS R5', 'Sony A7R IV',
        'Dải tương phản động mở rộng (HDR)', 'Có kết cấu', 'Mịn màng', 'Sạch sẽ', 'Không tì vết', 'Giải phẫu hoàn hảo',
        'Bàn tay hoàn hảo', 'Chính xác', 'Chính xác về mặt vật lý', 'ISO 50', 'ISO 100', 'Độ nhiễu thấp',
        'Không có lỗi nén', 'Độ sâu trường ảnh (DoF)', 'Thịnh hành trên ArtStation', 'Flickr', '500px', 'Behance',
        'Phim Fuji Velvia', 'Phim Kodak Portra 400', 'Phim Ilford HP5', 'Phim Cinestill 800T'
    ],
    lightingCategory: [
        'Ánh sáng điện ảnh', 'Ánh sáng kịch tính', 'Ánh sáng thể tích', 'Tia sáng của Chúa', 'Tia hoàng hôn', 'Ánh sáng viền', 'Ngược sáng', 'Bóng đen',
        'Giờ vàng', 'Giờ xanh', 'Bình minh', 'Hoàng hôn', 'Nắng trưa', 'Ban đêm', 'U ám',
        'Ánh sáng dịu', 'Ánh sáng gắt', 'Ánh sáng studio', 'Chiếu sáng ba điểm', 'Ánh sáng Rembrandt', 'Tối (Low-key)', 'Sáng (High-key)',
        'Đèn neon', 'Ánh sáng Cyberpunk', 'Phát quang sinh học', 'Phát sáng', 'Óng ánh', 'Holographic',
        'Ánh sáng tự nhiên', 'Ánh sáng mặt trời', 'Ánh sáng mặt trăng', 'Ánh sao', 'Ánh nến', 'Ánh lửa', 'Ánh đèn lồng',
        'Ánh sáng kỳ lạ', 'Ánh sáng ma thuật', 'Ánh sáng khí quyển', 'Ánh sáng tâm trạng', 'Tương phản sáng tối (Chiaroscuro)',
        'Sương mù', 'Mờ ảo', 'Làn sương', 'Ánh sáng dưới nước', 'Cực quang', 'Đèn laser', 'Ánh sáng sân khấu', 'Đèn chiếu',
        'Đèn đường', 'Hiện tượng tụ quang', 'Luồng sáng', 'Ánh sáng nhấp nháy', 'Ánh sáng pulsating', 'Tán xạ dưới bề mặt'
    ],
    colorCategory: [
        'Màu sắc rực rỡ', 'Đơn sắc', 'Màu pastel', 'Đen và trắng', 'Màu bổ túc',
        'Màu tương đồng', 'Màu bộ ba', 'Bảng màu neon', 'Bảng màu ấm', 'Bảng màu lạnh',
        'Tông màu xanh dương', 'Tông màu đỏ', 'Màu nâu đỏ', 'Song sắc', 'Tam sắc', 'Đa sắc', 'Óng ánh',
        'Holographic', 'Technicolor', 'Màu trầm', 'Tông màu đất', 'Tông màu đá quý', 'Bão hòa',
        'Khử bão hòa', 'Tương phản cao', 'Tương phản thấp', 'Chỉnh màu', 'Bảng màu điện ảnh',
        'Màu phim cổ điển', 'Gradient', 'Cầu vồng', 'Quang phổ', 'Màu sắc ảo giác', 'Màu sắc thanh tao',
        'Màu tối và tâm trạng', 'Màu tươi sáng và vui vẻ', 'Màu điện tử', 'Màu kim loại',
        'Vàng', 'Bạc', 'Đồng', 'Đồng thau', 'Màu sắc đậm đà', 'Màu sắc sâu', 'Màu sắc nhẹ nhàng', 'Màu phai',
        'Vệt màu', 'Màu chọn lọc', 'Màu sắc hài hòa', 'Bảng màu địa ngục', 'Bảng màu thiên thể',
        'Cam và xanh lơ', 'Bảng màu Synthwave', 'Màu axit'
    ],
    compositionCategory: [
        'Góc chụp rộng', 'Chụp cận cảnh', 'Chụp siêu cận cảnh', 'Chụp toàn thân', 'Chân dung',
        'Phong cảnh', 'Góc nghiêng Hà Lan', 'Góc chụp thấp', 'Góc chụp cao', 'Góc nhìn từ trên xuống', 'Góc nhìn từ dưới lên',
        'Bokeh', 'Độ sâu trường ảnh nông', 'Độ sâu trường ảnh sâu', 'Quy tắc một phần ba', 'Đường dẫn',
        'Đối xứng', 'Bất đối xứng', 'Bố cục động', 'Bố cục trung tâm', 'Bố cục lệch tâm',
        'Ống kính mắt cá', 'Chụp macro', 'Chụp tele', 'Chụp lia máy', 'Chụp nghiêng máy', 'Chụp cẩu', 'Dolly zoom',
        'Chụp qua vai', 'Góc nhìn thứ nhất (POV)', 'Tỷ lệ vàng', 'Khung trong khung',
        'Không gian âm', 'Chụp đầu', 'Chụp bán thân', 'Chụp kiểu cao bồi', 'Chụp toàn cảnh', 'Khung hình nghiêng',
        'Ống kính 24mm', 'Ống kính 35mm', 'Ống kính 50mm', 'Ống kính 85mm', 'Ống kính 135mm', 'Ống kính 200mm', 'Phối cảnh cưỡng bức', 'Toàn cảnh (Panoramic)',
        'Chụp xa', 'Chụp trung cảnh', 'Bố cục đường chéo', 'Chụp bằng drone', 'Góc nhìn GoPro', 'Thước phim tư liệu',
        'Khung hình độc đáo', 'Chụp từ trên xuống (Flat lay)', 'Hiệu ứng Ken Burns', 'Chụp Snorricam', 'Nhiếp ảnh Tilt-shift'
    ],
    effectsCategory: [
        'Lóa ống kính', 'Phát sáng', 'Tia sáng của Chúa', 'Quang sai màu', 'Mờ chuyển động', 'Anamorphic', 'Vệt sáng',
        'Hiệu ứng hạt', 'Tia lửa', 'Khói', 'Sương mù', 'Làn khói', 'Sương', 'Mưa', 'Tuyết', 'Mưa phùn',
        'Hạt bụi', 'Nhiễu hạt phim', 'Tối góc', 'Rò rỉ ánh sáng', 'Hiệu ứng nở hoa', 'Hiệu ứng Glitch', 'Vạch quét',
        'Hiệu ứng VHS', 'Điểm ảnh hóa', 'Bán sắc', 'Chồng ảnh', 'Phơi sáng dài', 'Tua nhanh thời gian',
        'Gợn nước', 'Than hồng', 'Hồ quang điện', 'Phép thuật', 'Vụ nổ năng lượng', 'Trường lực',
        'Méo hình', 'Sóng nhiệt', 'Tán xạ khí quyển', 'Như mơ', 'Thanh tao', 'Vụ nổ',
        'Pháo hoa', 'Nước bắn', 'Bong bóng', 'Hoa giấy', 'Lung linh', 'Hạt lơ lửng', 'Hào quang',
        'Khiên năng lượng', 'Méo mó thời gian', 'Luồng dữ liệu', 'Họa tiết fractal', 'Hóa lỏng', 'Hiệu ứng Lensbaby'
    ],
    subjectPoseCategory: [
        'Đứng', 'Ngồi', 'Nằm', 'Chạy', 'Nhảy', 'Đi bộ', 'Nhìn vào người xem',
        'Nhìn đi chỗ khác', 'Tư thế hành động', 'Tư thế động', 'Tư thế thư giãn', 'Trầm tư', 'Thanh thản',
        'Chiến thắng', 'Thất bại', 'Ngồi xổm', 'Dựa', 'Vươn vai', 'Nhảy múa', 'Chiến đấu',
        'Thiền định', 'Cầu nguyện', 'Vươn tới', 'Khoanh tay', 'Chống hông', 'Nhìn nghiêng',
        'Góc nhìn ba phần tư', 'Nhìn từ phía sau', 'Đang chuyển động', 'Giữa không trung', 'Lơ lửng', 'Bơi lội', 'Quỳ gối',
        'Cúi chào', 'Vẫy tay', 'Chỉ tay', 'Hét lớn', 'Thì thầm', 'Cười', 'Khóc', 'Cười nhếch mép',
        'Cau mày', 'Tư thế phòng thủ', 'Tư thế tấn công', 'Tư thế thanh lịch', 'Tư thế mạnh mẽ',
        'Ẩn nấp', 'Nhìn trộm', 'Co rúm', 'Ngắm sao', 'Nhảy vọt trên không', 'Tư thế thách thức',
        'Triệu hồi', 'Thi triển phép thuật', 'Cầm một quả cầu phát sáng', 'Rút gươm'
    ],
    outfitCategory: [
        'Trang phục thường ngày', 'Âu phục trang trọng', 'Váy dạ hội', 'Áo giáp khoa học viễn tưởng', 'Áo giáp kỳ ảo', 'Kimono', 'Áo hoodie',
        'Áo khoác da', 'Váy cổ điển', 'Trang phục Steampunk', 'Quần áo Cyberpunk', 'Quân phục',
        'Bộ đồ du hành vũ trụ', 'Áo choàng truyền thống', 'Váy thời Victoria', 'Gothic lolita', 'Trang phục Punk rock',
        'Trang phục công sở', 'Váy cưới', 'Áo khoác phòng thí nghiệm', 'Trang phục cô gái phép thuật', 'Áo giáp hiệp sĩ',
        'Áo giáp Samurai', 'Trang bị Viking', 'Quần áo rách rưới hậu tận thế', 'Trang bị nhà thám hiểm', 'Trang phục hoàng gia',
        'Quần áo nông dân', 'Sờn và rách', 'Sạch sẽ và nguyên sơ', 'Mũ đội đầu công phu', 'Áo choàng bay',
        'Áo choàng có mũ', 'Ủng nặng', 'Găng tay thanh lịch', 'Trang sức tinh xảo', 'Mặt nạ phòng độc', 'Kính bảo hộ',
        'Vương miện', 'Vương miện nhỏ', 'Ruy băng', 'Ren', 'Vải bò', 'Áo khoác dài', 'Trang phục siêu anh hùng', 'Trang phục lễ hội',
        'Bộ đồ cơ khí sinh học', 'Bộ giáp Exosuit', 'Áo giáp chạm khắc tinh xảo', 'Cổ ngữ phát sáng', 'Áo giáp năng lượng'
    ],
    environmentCategory: [
        'Rừng', 'Rừng rậm', 'Sa mạc', 'Núi', 'Đại dương', 'Bãi biển', 'Cảnh quan thành phố', 'Thành phố tương lai',
        'Thành phố đổ nát', 'Thành phố dưới nước', 'Hành tinh xa lạ', 'Núi lửa', 'Hang động', 'Lâu đài', 'Ngôi đền',
        'Nội thất tàu vũ trụ', 'Hẻm Cyberpunk', 'Xưởng Steampunk', 'Thư viện ma thuật',
        'Khu rừng bị phù phép', 'Vùng đất hoang tàn hậu tận thế', 'Đồng bằng cằn cỗi', 'Lãnh nguyên Bắc cực', 'Đầm lầy',
        'Đồng cỏ', 'Đảo nổi', 'Hang động pha lê', 'Bên trong một cỗ máy khổng lồ', 'Trên mặt trăng',
        'Trong không gian sâu', 'Phong cảnh siêu thực', 'Cảnh mộng', 'Cảnh địa ngục', 'Cõi thiên đàng',
        'Phong cảnh băng hà', 'Sân thượng nhà chọc trời', 'Ngôi nhà nhỏ ấm cúng', 'Khu chợ nhộn nhịp', 'Nhà máy bỏ hoang',
        'Phòng ngai vàng', 'Phòng khiêu vũ', 'Cầu chỉ huy tàu vũ trụ', 'Khu rừng phát quang sinh học', 'Phong cảnh bị tha hóa',
        'Vườn hoa anh đào', 'Rừng tre', 'Thành phố trên mây', 'Thư viện liên không gian', 'Quả cầu Dyson',
        'Thế giới vành đai', 'Tinh vân thiên hà', 'Trái Đất hậu nhân loại', 'Thành phố Solarpunk'
    ],
    materialsCategory: [
        'Kim loại', 'Gỗ', 'Đá', 'Thủy tinh', 'Vải', 'Da', 'Nhựa', 'Cao su', 'Lụa', 'Nhung',
        'Cotton', 'Len', 'Lông thú', 'Vảy', 'Lông vũ', 'Xương', 'Pha lê', 'Đá quý', 'Cẩm thạch', 'Đá hoa cương',
        'Bê tông', 'Gạch', 'Crom', 'Vàng', 'Bạc', 'Đồng', 'Đồng thau', 'Kim loại gỉ',
        'Kim loại được đánh bóng', 'Bề mặt mờ', 'Bề mặt bóng', 'Trong mờ', 'Mờ đục', 'Vật liệu phát sáng',
        'Vật liệu holographic', 'Kim loại lỏng', 'Kết cấu hữu cơ', 'Kết cấu thô', 'Kết cấu mịn',
        'Kết cấu dệt', 'Chi tiết khắc', 'Chạm rỗng', 'Thép Damascus', 'Sợi carbon', 'Đá vỏ chai',
        'Ngọc bích', 'Hổ phách', 'Sứ', 'Kính màu', 'Họa tiết mạch điện', 'Dung nham', 'Băng',
        'Pha lê lỏng', 'Vảy óng ánh', 'Sợi carbon dệt', 'Đá vỏ chai được đẽo', 'Nấm phát quang sinh học'
    ],
};